#!/usr/bin/env bash

INPUT_DATA=~/data
FCN_CACHE=~/data_fcn
LC_CACHE=~/data_lc
MODEL=~/model
DRIVE_ID=HT052_1458600142
DRIVE_URI=s3://asset.ama.here.com/65e94cd2-a2d2-46cc-9116-ea1702f592c1
ASSET_ID=78480985

export PYTHONPATH=$PYTHONPATH:~/source/fcn

python top_down_image_generator_and_line_predictor.py \
    --drive-id $DRIVE_ID \
    --drive-uri $DRIVE_URI \
    --model $MODEL/had_6cm_mc_batchnrm2_100_rate0.1/model-549701 \
    --cache $FCN_CACHE \
    --clear-cache \
    --verbosity 1

python line_connector.py \
  --images  $FCN_CACHE/results \
  --poses   $INPUT_DATA/$ASSET_ID-pose.csv \
  --chunks  $INPUT_DATA/$ASSET_ID.csv \
  --drives  $LC_CACHE/drives.txt \
  --config  ./conf.json \
  --verbosity 1 \
  --visualize 2 \
  --fuses   $LC_CACHE/fuse/ \
  --tagged  $LC_CACHE/input/fuse_tagged/ \
  --cache   $LC_CACHE
  --clear_cache
