#!/usr/bin/env bash

INPUT_DATA=~/data
FCN_CACHE=~/data_fcn
LC_CACHE=~/data_lc
MODEL=~/model
DRIVE_ID=HT073_1479214910
DRIVE_URI=s3://asset.ama.here.com/888a6dda-5291-4759-97c3-e505e06a27d1
ASSET_ID=7230177

export PYTHONPATH=$PYTHONPATH:~/source/fcn

python top_down_image_generator_and_line_predictor.py \
    --drive-id $DRIVE_ID \
    --drive-uri $DRIVE_URI \
    --model $MODEL/had_6cm_mc_batchnrm2_100_rate0.1/model-549701 \
    --cache $FCN_CACHE \
    --clear-cache \
    --verbosity 1

python line_connector.py \
  --images  $FCN_CACHE/results/$DRIVE_ID \
  --poses   $INPUT_DATA/input/poses/ \
  --chunks  $INPUT_DATA/input/input/chunks/ \
  --config  ./conf.json \
  --verbosity 1 \
  --visualize 1 \
  --fuses   $LC_CACHE/fuse/ \
  --tagged  $LC_CACHE/input/fuse_tagged/ \
  --cache   $LC_CACHE \
  --clear_cache
