#!/usr/bin/env bash

INPUT_DATA=~/HT002_1412347127
FCN_CACHE=~/data_fcn
LC_CACHE=~/data_lc
MODEL=~/model
DRIVE_ID=HT002_1412347127
DRIVE_URI=s3://asset.ama.here.com/26549bb2-8425-4559-971a-4ded905774aa
ASSET_ID=7230177

IMAGES=$INPUT_DATA/FeatureCollections/HT002_1412347127_1096382345000000/RGB

export PYTHONPATH=$PYTHONPATH:~/source/fcn


python line_predictor.py \
    --drive-id $DRIVE_ID \
    --images $IMAGES \
    --model $MODEL/had_6cm_mc_batchnrm2_100_rate0.1/model-549701 \
    --cache $FCN_CACHE \
    --verbosity 1


python line_connector.py \
  --images  $FCN_CACHE/results \
  --poses   $INPUT_DATA/$ASSET_ID-pose.csv \
  --chunks  $INPUT_DATA/$ASSET_ID.csv \
  --drives  $LC_CACHE/drives.txt \
  --config  ./conf.json \
  --verbosity 1 \
  --visualize 2 \
  --fuses   $LC_CACHE/fuse/ \
  --tagged  $LC_CACHE/input/fuse_tagged/ \
  --cache   $LC_CACHE \
  --clear_cache
