#!/usr/bin/env bash

CACHE="/tmp/sslc"
CACHE_PREV="/tmp/sslc_prev"
rm -rf $CACHE_PREV
mv $CACHE $CACHE_PREV

./scripts/runall \
  --images  ~/data/images/ \
  --poses   ~/data/poses/ \
  --chunks  ~/data//chunks/ \
  --drives  ~/data/drives.txt \
  --tracker "sort" \
  --config  ./conf.json \
  --verbosity 1 \
  --visualize 0 \
  --fuses   $CACHE/output/fuse/ \
  --tagged  $CACHE/fuse_tagged/ \
  --cache   $CACHE


diff -r $CACHE_PREV $CACHE
