#!/usr/bin/env bash

CACHE="/home/mo/Desktop/tmp/"

./scripts/runall \
  --images  ~/data_ian/input/images/ \
  --fuses   ~/data_ian/input/fuse/ \
  --tagged  ~/data_ian/input/fuse_tagged/ \
  --poses   ~/data_ian/input/poses/ \
  --chunks  ~/data_ian/input/chunks/ \
  --drives  ~/Desktop/drive_poc.txt \
  --tracker "sort" \
  --config  ./conf.json \
  --cache   $CACHE
