#!/usr/bin/env bash

cd modules/evaluate

#clean up past runs
rm -f data
rm -f tracks
rm -rf stat_out/
rm -rf out/
rm -f log.txt
rm -f seqs.csv

#link to data
ln -s ../preprocess/out data
ln -s ../trackers/sort/output tracks

echo $(date) "Making a list of sequences"
./make_seq_list.py >> log.txt

echo $(date) "Converting MOT to JSONs"
./mot2json.py seqs.csv >> log.txt

echo $(date) "Running evaluation (groundtruth.json vs hypotheses.json)"
./evaluate.py

cd ../..


