#!/usr/bin/env bash

while [[ "$#" > 1 ]]; do case $1 in
    --input) input_evaluate="$2";;
    --tracks) tracks_evaluate="$2";;
    --output) output_evaluate="$2";;
    *) echo "Usage: evaluate --input [path] --tracks [path] --output [path]"; exit 1;;
  esac; shift; shift
done

if [[ -z "$input_evaluate" ]] || [[ -z "$tracks_evaluate" ]] || [[ -z "$output_evaluate" ]] ; then
  echo "Usage: evaluate --input [path] --tracks [path] --output [path]"
  exit 1
fi

mkdir $output_evaluate

echo $(date) >> $output_evaluate/log.txt

echo $(date) "Making a list of sequences"
./modules/evaluate/make_seq_list.py --input $input_evaluate --tracks $tracks_evaluate --output $output_evaluate/seqs.csv >> $output_evaluate/log.txt

echo $(date) "Converting MOT to JSONs"
./modules/evaluate/mot2json.py --input $output_evaluate/seqs.csv --output $output_evaluate/jsons >> $output_evaluate/log.txt

echo $(date) "PYMOT: computing the stats"
mkdir $output_evaluate/stat
for i in $(ls $input_evaluate)
do
  ./modules/evaluate/pymot/pymot.py -a $output_evaluate/jsons/$i/groundtruth.json -b $output_evaluate/jsons/$i/hypotheses.json > $output_evaluate/stat/$i.stat
done

echo $(date) "Summarizing the stats"
./modules/evaluate/evaluate.py --input $output_evaluate/stat/
