#!/usr/bin/env bash

while [[ "$#" > 1 ]]; do case $1 in
    --input)  input_fuse="$2";;
    --tracks) tracks_fuse="$2";;
    --output) output_fuse="$2";;
    --config) config_fuse="$2";;
    --input-root) input_root="$2";;
    *) echo "Usage: fuse --input path/to/MOT_data --tracks path/to/tracks --output path/to/tmp --config path/to/config_file --input-root path/to/drive_data"; exit 1;;
  esac; shift; shift
done

if  [[ -z "$input_fuse"   ]] || \
    [[ -z "$tracks_fuse"  ]] || \
    [[ -z "$output_fuse"  ]] || \
    [[ -z "$config_fuse"  ]] || \
    [[ -z "$input_root"   ]] ; then
  echo "Usage: fuse --input path/to/MOT_data --tracks path/to/tracks --output path/to/tmp --config path/to/config_file --input-root path/to/drive_data"
  exit 1
fi

mkdir $output_fuse

echo $(date) >> $output_fuse/log.txt

./modules/fuse/make_seq_list.py \
  --input  $input_fuse \
  --tracks $tracks_fuse \
  --output $output_fuse/seqs.csv \
  >> $output_fuse/log.txt

echo $(date) "Fusion of tracking output..."

echo "Fusion config:"
./modules/fuse/print_param.py --config $config_fuse

./modules/fuse/fuse.py \
  --input  $output_fuse/seqs.csv \
  --output $output_fuse/fused \
  --config $config_fuse \
  --input-root $input_root \
  >> $output_fuse/log.txt
