#!/usr/bin/env bash

while [[ "$#" > 1 ]]; do case $1 in
    --input)      INPUT_POSTPROCESS="$2";;
    --tracks)     TRACKS_POSTPROCESS="$2";;
    --output)     OUTPUT_POSTPROCESS="$2";;
    --config)     CONFIG_POSTPROCESS="$2";;
    --verbosity)  VERBOSITY_POSTPROCESS="$2";;
    *) echo "Usage error"; exit 1;;
  esac; shift; shift
done

if [[ $VERBOSITY_POSTPROCESS -ge 1 ]] ; then
  echo -e "\033[1;31m"$(date)"\033[0m" "Postprocessing"
fi

mkdir -p $OUTPUT_POSTPROCESS

./modules/postprocess/print_param.py \
  --config    $CONFIG_POSTPROCESS \
  --verbosity $VERBOSITY_POSTPROCESS

./modules/postprocess/make_seq_list.py \
  --input   $INPUT_POSTPROCESS \
  --tracks  $TRACKS_POSTPROCESS \
  --output  $OUTPUT_POSTPROCESS/seqs.csv \
  --verbosity $VERBOSITY_POSTPROCESS

./modules/postprocess/postprocess.py \
  --input   $OUTPUT_POSTPROCESS/seqs.csv \
  --output  $OUTPUT_POSTPROCESS/tracks \
  --config  $CONFIG_POSTPROCESS \
  --verbosity $VERBOSITY_POSTPROCESS
