#!/usr/bin/env bash

while [[ "$#" > 1 ]]; do case $1 in
    --input)  input_preprocess="$2";;
    --output) output_preprocess="$2";;
    --config) config_preprocess="$2";;
    *) echo "Usage: preprocess --input path/to/data --output path/to/tmp --config path/to/config_file"; exit 1;;
  esac; shift; shift
done

if [[ -z "$input_preprocess" ]] || [[ -z "$output_preprocess" ]] || [[ -z "$config_preprocess" ]] ; then
  echo "Usage: preprocess --input path/to/data --output path/to/tmp --config path/to/config_file"
  exit 1
fi

mkdir $output_preprocess

echo $(date) >> $output_preprocess/log.txt

echo $(date) "Preprocessing"

./modules/preprocess/print_param.py --config $config_preprocess

./modules/preprocess/highv1mot.py \
  --input  $input_preprocess \
  --output $output_preprocess/mot \
  --config $config_preprocess \
  >> $output_preprocess/log.txt
