#!/usr/bin/env bash

cd modules/preprocess

#clean up past runs
rm -f drive_jsons
rm -f JSONs
rm -rf ss_jsons/
rm -rf out/
rm -f log.txt

#link to data
ln -s ../../data/sample_json drive_jsons

echo $(date) "Breaking up big (drive) JSONs into small (surface) JSONs"
./break_json.py >> log.txt

ln -s ss_jsons JSONs
echo $(date) "Saving JSONs in MOT format"
./json2mot.py >> log.txt

cd ../..


