#!/usr/bin/env bash

while [[ "$#" > 1 ]]; do case $1 in
    --input)  input_path="$2";;
    --poses)  poses_path="$2";;
    --output) cache="$2";;
    --drives) drive_list="$2";;
    *) echo "Usage: runall [--input path/to/data] --drives path/to/drive_names_txt --output path/to/tmp"; exit 1;;
  esac; shift; shift
done

if [[ -z $cache ]] ; then
  echo "Usage: runall [--input path/to/data] --drives path/to/drive_names_txt --output path/to/tmp"; exit 1
fi

MOT_CONFIG="./conf.json"

if [[ $input_path ]] ; then
  if mkdir $cache ; then
    if [[ -z $drive_list ]] ; then
      echo "Saving the drive names in $cache/preprocess"
      drive_list=$cache/preprocess/drive_list.txt
    fi
    ./scripts/preprocess  --input $input_path           --output $cache/preprocess  --config $MOT_CONFIG  --drives $drive_list  --poses $poses_path
    ./scripts/sort        --input $cache/preprocess/mot --output $cache/sort        --config $MOT_CONFIG
    ./scripts/postprocess --input $cache/preprocess/mot --output $cache/postprocess --config $MOT_CONFIG  --tracks $cache/sort/tracks
    # ./scripts/fuse        --input $cache/preprocess/mot --output $cache/fuse        --config $MOT_CONFIG  --tracks $cache/postprocess/tracks  --input-root $input_path
    # ./scripts/evaluate    --input $cache/preprocess/mot --output $cache/evaluate    --config $MOT_CONFIG  --tracks $cache/sort/tracks
  else
    echo "Output path is not empty.. Please enter an empty path for outputs."
  fi
fi

read -sp "Press [ENTER] to Visualize"; echo ""
rm -rf $cache/visualize
./scripts/visualize --input $cache/preprocess/mot --output $cache/visualize --config $MOT_CONFIG --tracks $cache/postprocess/tracks

