#!/usr/bin/env bash

while [[ "$#" > 1 ]]; do case $1 in
    --input) input_sort="$2";;
    --output) output_sort="$2";;
		--config) config_sort="$2";;
    *) echo "Usage: sort --input [path] --output [path] --config [path]"; exit 1;;
  esac; shift; shift
done

if [[ -z "$input_sort" ]] || [[ -z "$output_sort" ]] || [[ -z "$config_sort" ]] ; then
  echo "Usage: sort --input [path] --output [path] --config [path]"
  exit 1
fi

mkdir $output_sort

echo $(date) >> $output_sort/log.txt

echo $(date) "Tracking: Running the SORT tracker"

echo "SORT tracker config:"
./modules/trackers/sort/print_param.py --config $config_sort

./modules/trackers/sort/sort.py \
  --input $input_sort \
  --output $output_sort/tracks \
  --config $config_sort \
  >> $output_sort/log.txt


