#!/usr/bin/env bash

while [[ "$#" > 1 ]]; do case $1 in
    --input) input_visualize="$2";;
    --tracks) tracks_visualize="$2";;
    --output) output_visualize="$2";;
    --config) config_visualize="$2";;
    *) echo "Usage: visualize --input path/to/MOT_data --tracks path/to/tracks --output path/to/tmp --config path/to/config_file"; exit 1;;
  esac; shift; shift
done

if  [[ -z "$input_visualize"  ]] || \
    [[ -z "$tracks_visualize" ]] || \
    [[ -z "$output_visualize" ]] || \
    [[ -z "$config_visualize" ]] ; then
  echo "Usage: visualize --input path/to/MOT_data --tracks path/to/tracks --output path/to/tmp --config path/to/config_file"
  exit 1
fi

mkdir $output_visualize

echo $(date) >> $output_visualize/log.txt

echo "Visualization config:"
./modules/visualize/print_param.py --config $config_visualize

./modules/visualize/make_seq_list.py \
  --input $input_visualize \
  --tracks $tracks_visualize \
  --output $output_visualize/seqs.csv \
  >> $output_visualize/log.txt

echo $(date) "Visualization..."

./modules/visualize/disp.py \
  --input $output_visualize/seqs.csv \
  --config $config_visualize
