#!/usr/bin/env bash

while [[ "$#" > 1 ]]; do case $1 in
    --input)      INPUT_VISUALIZE="$2";;
    --tracks)     TRACKS_VISUALIZE="$2";;
    --output)     OUTPUT_VISUALIZE="$2";;
    --config)     CONFIG_VISUALIZE="$2";;
    --verbosity)  VERBOSITY_VISUALIZE="$2";;
    *) echo "Visualization: usage error"; exit 1;;
  esac; shift; shift
done

if [[ $VERBOSITY_VISUALIZE -ge 1 ]] ; then
  echo -e "\033[1;31m"$(date)"\033[0m" "Visualization"
fi

mkdir -p $OUTPUT_VISUALIZE

./modules/visualize/print_param.py \
  --config    $CONFIG_VISUALIZE \
  --verbosity $VERBOSITY_VISUALIZE

./modules/visualize/make_seq_list.py \
  --input     $INPUT_VISUALIZE \
  --tracks    $TRACKS_VISUALIZE \
  --output    $OUTPUT_VISUALIZE/seqs.csv \
  --verbosity $VERBOSITY_VISUALIZE

./modules/visualize/disp.py \
  --input     $OUTPUT_VISUALIZE/seqs.csv \
  --config    $CONFIG_VISUALIZE \
  --verbosity $VERBOSITY_VISUALIZE
